name: Optimize Images
on:
  push:
    branches:
      - website
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Commit changes direct to master
        run: |
          echo "Adding images"
          git config --global user.email "evan@geopjr.dev"
          git config --global user.name "GeopJr"
          git add static/
          echo "Committing changes"
          git diff-index --quiet HEAD || git commit -m "Optimised images"
          git push
